@startuml
class de.swt.gui.classroom.AdminEditClassroomPanel {
- JPanel mainPanel
- JTextField gradeTextField
- JButton resetButton
- JButton migrateButton
- JButton deleteButton
- JLabel gradeLabel
- JLabel errorLabel
- Course course
+ void updateGUI()
+ void setupListeners()
- void setupGUI(String,String,String,String)
+ String getGrade()
+ void migrateFunction()
+ void resetFunction()
+ void deleteFunction()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.login.LoginGUI {
- JPanel mainPanel
- JButton loginButton
- JTextField usernameTextField
- JPasswordField passwordField
- JLabel loginLabel
- JLabel passwordLabel
- JLabel usernameLabel
- JPanel subPanel
- JLabel errorLabel
+ void updateGUI()
+ void setupListeners()
- void setupGUI(String,String,String,String)
+ String getPassword()
+ String getUsername()
- void login()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.classroom.GradePanel {
- Course course
- JPanel mainPanel
- JButton enterButton
- JButton editButton
- JLabel dateLabel
- JLabel teacherLabel
- JLabel nextDateLabel
- JLabel thisTeacherLabel
- JLabel gradeHeaderLabel
- EditClassroomPanel editClassroomPanel
- AdminEditClassroomPanel adminEditClassroomPanel
+ void updateGUI()
+ void setupListeners()
- void setupGUI(String,String,String,String,String)
- String getNextSessionDate()
- void enterFunction()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.workspace.GroupButtonPanel {
- JPanel mainPanel
- JButton watchButton
- JButton terminateButton
- Group group
- void setupGUI(String,String)
+ void updateGUI()
+ void setupListeners()
- void leaveFunction()
- void terminateFunction()
- void watchFunction()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.GUIManager {
- Language language
- AccountType accountType
- LoginGUI loginGUI
- ClassroomGUI classroomGUI
- WorkspaceGUI workspaceGUI
- List<GUI> childrenGUI
- Client client
- int drawableObjectCounter
- WorkspaceState workspaceState
+ void setupGUIS()
+ void secondSetup()
+ void updateGUIS()
+ void switchToLoginGUI()
+ void switchToClassRoomGUI()
+ void switchToWorkspaceGUI()
+ void addToDrawPanel(DrawableObject)
+ boolean removeLastDrawnObject()
+ boolean removeLastAnnotations()
+ void clearDrawingPanel()
+ DrawableObject[] getDrawnObjects()
+ DrawableObject[] getAnnotations()
+ void addDrawableObjects(DrawableObject[])
+ void saveWorkspace(File)
+ void loadWorkspace(File)
+ void syncWorkspace(byte[])
+ void syncSingleObject(DrawableObject)
- void removeAllIndexedObjects(DrawableObject[])
+ int increaseObjectCounter()
+ ArrayList<Group> getRelevantGroups()
- void timeUpdater()
- void setTimeTilLTermination(int)
+ void sendRequest(User)
+ void sendTaskProposition()
+ void setTask(String)
+ void removeLastObject()
}
class de.swt.gui.workspace.RequestPanel {
- JPanel mainPanel
+ JButton acceptButton
+ JButton denyButton
- User user
- JLabel requestLabel
+ void updateGUI()
- void setupGUI(String,String,String)
+ void setupListeners()
+ void acceptFunction()
+ void denyFunction()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.workspace.CreateGroupPanel {
+ JPanel mainPanel
- JTextField numberTextField
- JTextField sizeTextField
- JTextField durationTextField
+ JButton createButton
- JLabel headerLabel
- JLabel numberLabel
- JLabel sizeLabel
- JLabel durationLabel
- JLabel unitLabel
- void setupGUI(String,String,String,String,String,String)
+ void updateGUI()
+ void setupListeners()
+ int getNumberText()
+ int getSizeText()
+ int getDurationText()
- void createFunction()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.workspace.UserButtonPanel {
- JPanel mainPanel
- JButton kickButton
- User user
- void setupGUI(String)
+ void updateGUI()
+ void setupListeners()
- void kickFunction()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.classroom.EditClassroomPanel {
- JButton addButton
- JPanel mainPanel
- JTextField studentTextField
- JLabel studentTextFieldLabel
- JButton removeButton
- Course course
- void setupGUI(String,String,String)
+ void updateGUI()
+ void setupListeners()
- void removeFunction()
+ String getStudent()
+ void addFunction()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.workspace.DrawablePanel {
- JPanel mainPanel
- JButton taskButton
+ JPanel drawPanel
- JLabel remainingLabel
- JButton showTaskButton
- Stack<DrawableObject> drawableObjects
- ShowTaskPanel showTaskPanel
- int objectCounter
- void setupGUI(String,String,String)
+ void updateGUI()
+ void setupListeners()
- void initForAccountType()
+ void setTask(String)
+ void addToDrawPanel(DrawableObject)
+ void removeInteraction()
+ void addInteraction()
+ boolean removeLastDrawnObject()
+ DrawableObject[] getDrawnObjects()
+ DrawableObject[] getAnnotations()
+ boolean removeLastAnnotations()
+ void removeAllIndexedObjects(DrawableObject[])
+ void removeEditingOptions()
+ void addEditingOptions()
+ void setTimeTillTermination(int)
+ void removeLastObject()
+ int increaseObjectCounter()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.classroom.CreateClassroomPanel {
- JPanel mainPanel
- JTextField gradeNameTextField
- JTextField teacherTextField
- JTextField dateTextField
- JButton doneButton
- JLabel gradeLabel
- JLabel gradeNameLabel
- JLabel teacherLabel
- JLabel dateLabel
- JLabel errorLabel
- JTextField gradeTextField
+ void updateGUI()
+ void setupListeners()
- void setupGUI(String,String,String,String,String)
- String getGradeName()
- String getTeacher()
- String getDate()
- void doneFunction()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.workspace.CreateTaskPanel {
- JPanel mainPanel
- JTextArea taskTextArea
- JPanel filePanel
- JButton selectFileButton
- JLabel headerLabel
- JLabel pictureLabel
- JLabel selectedFileLabel
- JButton createButton
- JScrollPane taskScrollPanel
- File selectedFile
- void setupGUI(String,String,String)
+ void updateGUI()
+ void setupListeners()
- void fileChooserFunction()
+ String getTaskText()
+ File getSelectedFile()
+ void createFunction()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.workspace.ShowTaskPanel {
- JPanel mainPanel
- JTextPane taskPane
- String task
+ void updateGUI()
+ void setupListeners()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.workspace.ObjectListPanel {
- JPanel mainPanel
- JButton switchButton
- JPanel objectButtons
- JLabel headerLabel
- JScrollPane objectScrollPanel
- String participants
- String groups
- String group
- boolean showGroups
- ArrayList<JButton> userButtons
- ArrayList<JButton> groupButtons
- void setupGUI(String,String,String)
+ void updateGUI()
+ void setupListeners()
+ void initForAccountType()
- JButton setupUserButton(User)
- JButton setupGroupButton(Group)
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.workspace.SelectGroupPanel {
- JPanel mainPanel
+ JButton startTaskButton
- JLabel selectGroupLabel
- JSlider groupSlider
- void setupGUI(String,String)
+ void updateGUI()
+ void setupListeners()
- void startTaskFunction()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.classroom.ClassroomGUI {
- JPanel mainPanel
- JLabel grade11Label
- JLabel grade10Label
- JLabel grade12Label
- JButton logoutButton
- JButton privateWorkspaceButton
- JButton supportButton
- JButton createClassroomButton
- JPanel gradePanel10
- JPanel gradePanel11
- JPanel gradePanel12
- JScrollPane scrollPanel10
- JScrollPane scrollPanel11
- JScrollPane scrollPanel12
- JPanel subPanel
- List<GradePanel> gradePanels
- CreateClassroomPanel createClassroomPanel
- void setupGUI(String,String,String,String,String,String)
+ void updateGUI()
+ void setupListeners()
- void logout()
+ void updateGradePanels()
- void removeAllGradePanels()
+ void initForAccountType()
- void removeEditButtonsFromGradePanels()
- void privateWorkspaceFunction()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.workspace.WorkspaceGUI {
- JPanel mainPanel
- JRadioButton writeRadioButton
- JRadioButton annotationRadioButton
- JButton logoutButton
- JPanel leftPanel
- JPanel menuPanel
- JPanel objectListPanelPanel
- JPanel midPanel
- JPanel rightPanel
- JButton sendTaskButton
- ObjectListPanel objectListPanel
- DrawablePanel drawablePanel
- SymbolListPanel symbolListPanel
- void setupGUI(String,String,String,String)
+ void updateGUI()
- void initForWorkspaceState()
+ void setupListeners()
- void initForAccountType()
- void logout()
+ void sendRequest(User)
+ void sendTaskProposition()
+ void setTimeTilLTermination(int)
+ void setTask(String)
+ void addToDrawPanel(DrawableObject)
+ boolean removeLastDrawnObject()
+ DrawableObject[] getDrawnObjects()
+ DrawableObject[] getAnnotations()
+ boolean removeLastAnnotations()
+ void removeAllIndexedObjects(DrawableObject[])
+ void removeLastObject()
+ int increaseObjectCounter()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.workspace.Menu {
- GUIManager guiManager
- JMenu file
- JMenuItem saveFile
- JMenuItem loadFile
- JMenu navigate
- JMenuItem logoff
- JMenuItem toClassroomGUI
- void setupMenu(String,String,String,String,String)
- void setupListeners()
}
abstract class de.swt.gui.GUI {
- GUIManager guiManager
- JPanel mainPanel
+ {abstract}void updateGUI()
+ {abstract}void setupListeners()
+ void setupPopupOnTop(JButton,GUI)
+ void setupPopupBelow(JButton,GUI)
+ void setupPopupToTheRight(JButton,GUI)
+ void setupMatchingPopup(JButton,GUI,GUI)
}
class de.swt.gui.workspace.SymbolListPanel {
- JPanel mainPanel
- JButton thumbsUpButton
- JButton thumbsDownButton
- JButton clearButton
- JPanel toolPanel
+ JPanel symbolPanel
- void setupGUI()
+ void updateGUI()
+ void setupListeners()
+ void removeAnnotationOptions()
+ void addAnnotationsOptions()
- void drawThumbUp()
- void drawThumbDown()
- void deleteLastDrawnObject()
+ void removeEditingOptions()
+ void addEditingOptions()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.useroverview.UserOverviewGUI {
- JPanel mainPanel
- void setupGUI()
+ void updateGUI()
+ void setupListeners()
- void initForAccountType()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}
class de.swt.gui.workspace.SubmitTaskPanel {
- JPanel mainPanel
- JButton yesButton
- JLabel checkLabel
- void setupGUI(String,String)
+ void updateGUI()
+ void setupListeners()
- void initForAccountType()
+ void yesFunction()
- void $$$setupUI$$$()
+ JComponent $$$getRootComponent$$$()
}


de.swt.gui.GUI <|-- de.swt.gui.classroom.AdminEditClassroomPanel
de.swt.gui.GUI <|-- de.swt.gui.login.LoginGUI
de.swt.gui.GUI <|-- de.swt.gui.classroom.GradePanel
de.swt.gui.GUI <|-- de.swt.gui.workspace.GroupButtonPanel
de.swt.gui.JFrame <|-- de.swt.gui.GUIManager
de.swt.gui.GUI <|-- de.swt.gui.workspace.RequestPanel
de.swt.gui.GUI <|-- de.swt.gui.workspace.CreateGroupPanel
de.swt.gui.GUI <|-- de.swt.gui.workspace.UserButtonPanel
de.swt.gui.GUI <|-- de.swt.gui.classroom.EditClassroomPanel
de.swt.gui.GUI <|-- de.swt.gui.workspace.DrawablePanel
de.swt.gui.GUI <|-- de.swt.gui.classroom.CreateClassroomPanel
de.swt.gui.GUI <|-- de.swt.gui.workspace.CreateTaskPanel
de.swt.gui.GUI <|-- de.swt.gui.workspace.ShowTaskPanel
de.swt.gui.GUI <|-- de.swt.gui.workspace.ObjectListPanel
de.swt.gui.GUI <|-- de.swt.gui.workspace.SelectGroupPanel
de.swt.gui.GUI <|-- de.swt.gui.classroom.ClassroomGUI
de.swt.gui.GUI <|-- de.swt.gui.workspace.WorkspaceGUI
de.swt.gui.workspace.JMenuBar <|-- de.swt.gui.workspace.Menu
de.swt.gui.JPanel <|-- de.swt.gui.GUI
de.swt.gui.GUI <|-- de.swt.gui.workspace.SymbolListPanel
de.swt.gui.GUI <|-- de.swt.gui.useroverview.UserOverviewGUI
de.swt.gui.GUI <|-- de.swt.gui.workspace.SubmitTaskPanel
@enduml