package de.swt.gui.workspace;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import de.swt.gui.GUI;
import de.swt.gui.GUIManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.io.File;

public class SubmitTaskPanel extends GUI {
    private JPanel mainPanel;
    private JButton yesButton;
    private JLabel checkLabel;

    public SubmitTaskPanel(GUIManager guiManager) {
        super(guiManager);
        this.add(mainPanel);

        switch (guiManager.getLanguage()) {
            case GERMAN -> setupGUI("Sicher?", "Ja");
            case ENGLISH -> setupGUI("Sure?", "Yes");
        }

    }

    private void setupGUI(String check, String yes) {
        this.checkLabel.setText(check);
        this.yesButton.setText(yes);
    }

    @Override
    public void updateGUI() {

    }

    @Override
    public void setupListeners() {
        yesButton.addActionListener(e -> yesFunction());
    }

    private void initForAccountType() {

    }

    public void yesFunction() {
        getGuiManager().saveWorkspace(new File("taskOutput.ser"));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(5, 5, 5, 5), -1, -1));
        yesButton = new JButton();
        yesButton.setText("Button");
        mainPanel.add(yesButton, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        checkLabel = new JLabel();
        checkLabel.setHorizontalAlignment(0);
        checkLabel.setText("Label");
        mainPanel.add(checkLabel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
