package de.swt.gui.classroom;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import de.swt.gui.GUI;
import de.swt.gui.GUIManager;
import de.swt.logic.course.Course;
import de.swt.logic.user.User;
import lombok.Setter;

import javax.swing.*;
import java.awt.*;
import java.rmi.RemoteException;
import java.util.ArrayList;

@Setter
public class AdminEditClassroomPanel extends GUI {
    private JPanel mainPanel;
    private JTextField gradeTextField;
    private JButton resetButton;
    private JButton migrateButton;
    private JButton deleteButton;
    private JLabel gradeLabel;
    private JLabel errorLabel;
    private Course course;

    public AdminEditClassroomPanel(GUIManager guiManager) {
        super(guiManager);
        this.setLayout(new BoxLayout(this, BoxLayout.X_AXIS));
        this.add(mainPanel);
        this.setBorder(BorderFactory.createEtchedBorder());
        switch (guiManager.getLanguage()) {
            case GERMAN -> setupGUI("neue Klassenstufe", "Zurücksetzen", "Migrieren", "Löschen");
            case ENGLISH -> setupGUI("New grade", "Reset", "Migrate", "Delete");
        }
    }

    @Override
    public void updateGUI() {

    }

    @Override
    public void setupListeners() {
        migrateButton.addActionListener(e -> migrateFunction());
        deleteButton.addActionListener(e -> deleteFunction());
        resetButton.addActionListener(e -> resetFunction());
    }

    private void setupGUI(String grade, String reset, String migrate, String delete) {
        this.gradeLabel.setText(grade);
        this.resetButton.setText(reset);
        this.migrateButton.setText(migrate);
        this.deleteButton.setText(delete);
    }

    public String getGrade() {
        return gradeTextField.getText();
    }

    public void migrateFunction() {
        int grade;
        try {
            grade = Integer.parseInt(getGrade());
            course.setGrade(grade);
            getGuiManager().getClient().getServer().updateCourse(course);
            errorLabel.setText("");
            migrateButton.setBackground(UIManager.getColor("JButton"));
        } catch (RemoteException e) {
            switch (getGuiManager().getLanguage()) {
                case GERMAN -> errorLabel.setText("Update fehlgeschlagen");
                case ENGLISH -> errorLabel.setText("Update failed");
            }
            migrateButton.setBackground(Color.RED);
        } catch (NumberFormatException e) {
            switch (getGuiManager().getLanguage()) {
                case GERMAN -> errorLabel.setText("Richtige Klassenstufe eingeben!");
                case ENGLISH -> errorLabel.setText("Enter correct grade!");
            }
            migrateButton.setBackground(Color.RED);
        }
    }

    public void resetFunction() {
        course.getUserIds().clear();
        try {
            getGuiManager().getClient().getServer().updateCourse(course);
            errorLabel.setText("");
            resetButton.setBackground(UIManager.getColor("JButton"));
        } catch (RemoteException e) {
            switch (getGuiManager().getLanguage()) {
                case GERMAN -> errorLabel.setText("Update fehlgeschlagen");
                case ENGLISH -> errorLabel.setText("Update failed");
            }
            resetButton.setBackground(Color.RED);
        }
    }

    public void deleteFunction() {
        try {
            getGuiManager().getClient().getServer().deleteCourse(course.getCourseId());
            errorLabel.setText("");
            deleteButton.setBackground(UIManager.getColor("JButton"));
        } catch (RemoteException e) {
            switch (getGuiManager().getLanguage()) {
                case GERMAN -> errorLabel.setText("Update fehlgeschlagen");
                case ENGLISH -> errorLabel.setText("Update failed");
            }
            deleteButton.setBackground(Color.RED);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 8, new Insets(5, 5, 5, 5), -1, -1));
        gradeLabel = new JLabel();
        gradeLabel.setText("Label");
        mainPanel.add(gradeLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        gradeTextField = new JTextField();
        mainPanel.add(gradeTextField, new GridConstraints(0, 1, 1, 7, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        migrateButton = new JButton();
        migrateButton.setText("Button");
        mainPanel.add(migrateButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        resetButton = new JButton();
        resetButton.setHorizontalAlignment(0);
        resetButton.setHorizontalTextPosition(11);
        resetButton.setText("Button");
        mainPanel.add(resetButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteButton = new JButton();
        deleteButton.setText("Button");
        mainPanel.add(deleteButton, new GridConstraints(1, 1, 1, 7, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        errorLabel = new JLabel();
        errorLabel.setHorizontalAlignment(0);
        errorLabel.setText("");
        mainPanel.add(errorLabel, new GridConstraints(2, 1, 1, 7, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        gradeLabel.setLabelFor(gradeTextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}


