package de.swt.gui.classroom;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import de.swt.gui.GUI;
import de.swt.gui.GUIManager;
import de.swt.logic.course.Course;
import de.swt.logic.user.User;
import de.swt.util.Client;
import de.swt.util.Language;
import de.swt.util.NextDate;

import javax.swing.*;
import java.awt.*;
import java.rmi.RemoteException;
import java.util.ArrayList;

public class CreateClassroomPanel extends GUI {
    private JPanel mainPanel;
    private JComboBox<String> gradeComboBox;
    private JTextField gradeNameTextField;
    private JTextField teacherTextField;
    private JTextField dateTextField;
    private JButton doneButton;
    private JLabel gradeLabel;
    private JLabel gradeNameLabel;
    private JLabel teacherLabel;
    private JLabel dateLabel;
    private JLabel errorLabel;

    public CreateClassroomPanel(GUIManager guiManager) {
        super(guiManager);
        switch (guiManager.getLanguage()) {
            case GERMAN -> this.setupGUI("Klassenstufe", "Klassenname", "Lehrer", "Termin", "Fertig");
            case ENGLISH -> this.setupGUI("Grade", "Grade name", "Teacher", "Date", "Done");
        }
    }

    @Override
    public void updateGUI() {

    }

    @Override
    public void setupListeners() {
        doneButton.addActionListener(e -> doneFunction());
    }

    private void setupGUI(String grade, String gradeName, String teacher, String date, String done) {
        this.gradeLabel.setText(grade);
        this.gradeNameLabel.setText(gradeName);
        this.teacherLabel.setText(teacher);
        this.dateLabel.setText(date);
        this.doneButton.setText(done);
        this.gradeComboBox.addItem("10");
        this.gradeComboBox.addItem("11");
        this.gradeComboBox.addItem("12");
    }

    private String getGradeName() {
        return gradeNameTextField.getText();
    }

    private String getTeacher() {
        return teacherTextField.getText();
    }

    private String getDate() {
        return dateTextField.getText();
    }

    private void doneFunction() {

        Course newCourse = new Course();

        try {
            newCourse.setGrade(gradeComboBox.getSelectedIndex() + 10);
            newCourse.setTeacherId(Integer.parseInt(getTeacher()));
            newCourse.setDates(NextDate.getDateFromString(getDate()));
            newCourse.setGradeName(getGradeName());
            errorLabel.setText("");
            doneButton.setBackground(UIManager.getColor("JButton"));
        } catch (Exception e) {
            switch (getGuiManager().getLanguage()) {
                case GERMAN -> errorLabel.setText("Bitte alles korrekt ausfüllen!");
                case ENGLISH -> errorLabel.setText("Please fill out everything!");
            }
            doneButton.setBackground(Color.RED);
        }

        try {
            getGuiManager().getClient().getServer().updateCourse(newCourse);
            doneButton.setBackground(UIManager.getColor("JButton"));
        } catch (RemoteException e) {
            e.printStackTrace();
            switch (getGuiManager().getLanguage()) {
                case GERMAN -> errorLabel.setText("Update fehlgeschlagen");
                case ENGLISH -> errorLabel.setText("Update failed");
            }
            doneButton.setBackground(Color.RED);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(6, 3, new Insets(5, 5, 5, 5), -1, -1));
        gradeComboBox = new JComboBox();
        mainPanel.add(gradeComboBox, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        gradeLabel = new JLabel();
        gradeLabel.setHorizontalAlignment(2);
        gradeLabel.setText("Label");
        mainPanel.add(gradeLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        gradeNameTextField = new JTextField();
        mainPanel.add(gradeNameTextField, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        teacherTextField = new JTextField();
        mainPanel.add(teacherTextField, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        dateTextField = new JTextField();
        mainPanel.add(dateTextField, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        gradeNameLabel = new JLabel();
        gradeNameLabel.setHorizontalAlignment(2);
        gradeNameLabel.setText("Label");
        mainPanel.add(gradeNameLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        teacherLabel = new JLabel();
        teacherLabel.setHorizontalAlignment(2);
        teacherLabel.setText("Label");
        mainPanel.add(teacherLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dateLabel = new JLabel();
        dateLabel.setHorizontalAlignment(2);
        dateLabel.setText("Label");
        mainPanel.add(dateLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        doneButton = new JButton();
        doneButton.setText("Button");
        mainPanel.add(doneButton, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        errorLabel = new JLabel();
        errorLabel.setText("");
        mainPanel.add(errorLabel, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        gradeLabel.setLabelFor(gradeComboBox);
        gradeNameLabel.setLabelFor(gradeNameTextField);
        teacherLabel.setLabelFor(teacherTextField);
        dateLabel.setLabelFor(dateTextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
