package de.swt.gui.classroom;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import de.swt.gui.GUI;
import de.swt.gui.GUIManager;
import de.swt.logic.course.Course;
import de.swt.logic.user.User;
import de.swt.logic.user.UserManager;
import lombok.Setter;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.rmi.RemoteException;
import java.util.ArrayList;

@Setter
public class EditClassroomPanel extends GUI {
    public JButton doneButton;
    public JButton cancelButton;
    private JPanel mainPanel;
    private JTextField studentTextField;
    private JComboBox<String> studentComboBox;
    private JLabel studentComboBoxLabel;
    private JLabel studentTextFieldLabel;
    private Course course;

    public EditClassroomPanel(GUIManager guiManager) {
        super(guiManager);
        this.setLayout(new BoxLayout(this, BoxLayout.X_AXIS));
        this.add(mainPanel);
        switch (guiManager.language) {
            case GERMAN -> this.setupGUI("<html>Schüler <br> hinzufügen</html>", "<html>Schüler <br> entfernen</html>", "Übernehmen", "Abbrechen");
            case ENGLISH -> this.setupGUI("Add student", "Remove student", "Commit", "Cancel");
        }
    }

    private void setupGUI(String student, String students, String done, String cancel) {
        this.studentTextFieldLabel.setText(student);
        this.studentComboBoxLabel.setText(students);
        this.doneButton.setText(done);
        this.cancelButton.setText(cancel);
    }

    public void updateGUI(ArrayList<User> students) {
        this.studentComboBox.removeAllItems();
        this.studentComboBox.addItem("");
        for (User student : students) {
            if (student.getCourse().contains(course.getId())) {
                this.studentComboBox.addItem(student.getId() + "");
            }
        }
    }

    public void updateGUI() {
    }

    public String getStudentToAdd() {
        return studentTextField.getText();
    }

    public String getStudentToRemove() {
        return (String) studentComboBox.getSelectedItem();
    }

    public void doneFunction() {

        UserManager userManager = guiManager.getClient().userManager;
        User user = null;

        if (!getStudentToAdd().equals("")) {
            user = userManager.getUserHashMap().get(Integer.parseInt(getStudentToAdd()));
            userManager.setSingleCourse(user, course.getId());
        }
        if (!getStudentToRemove().equals("")) {
            user = userManager.getUserHashMap().get(Integer.parseInt(getStudentToRemove()));
            userManager.removeSingleCourse(user, course.getId());
        }

        try {
            guiManager.getClient().server.sendUser(user, -1, true);
            guiManager.getClient().userManager.cacheAllUserData();
        } catch (RemoteException e) {
            e.printStackTrace();
        }

        ArrayList<User> list = new ArrayList<>(guiManager.getClient().userManager.getUserHashMap().values());
        guiManager.classroomGUI.updateGUI(list);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        studentTextFieldLabel = new JLabel();
        studentTextFieldLabel.setText("Label");
        mainPanel.add(studentTextFieldLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cancelButton = new JButton();
        cancelButton.setText("Button");
        mainPanel.add(cancelButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        studentTextField = new JTextField();
        mainPanel.add(studentTextField, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        studentComboBox = new JComboBox();
        mainPanel.add(studentComboBox, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        studentComboBoxLabel = new JLabel();
        studentComboBoxLabel.setText("Label");
        mainPanel.add(studentComboBoxLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        doneButton = new JButton();
        doneButton.setText("Button");
        mainPanel.add(doneButton, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        studentTextFieldLabel.setLabelFor(studentTextField);
        studentComboBoxLabel.setLabelFor(studentComboBox);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
